site_name: michaelrk02
docs_dir: src
site_dir: docs
theme:
  name: terminal
  features:
    - navigation.side.hide
nav:
  - Biografi: index.md
  - Portfolio: portfolio.md
  - Jasa: jasa.md
  - Tulisan: tulisan.md
markdown_extensions:
  attr_list:
  toc:
    permalink: '#'
  footnotes:
